In [ ]:
## Exercise 1: Array Creation and Attributes (15 points)

### Task 1.1: Create arrays using different methods (10 points)

Write code to create the following arrays:

1. A 1D array containing values from 0 to 9
2. A 2D array (3x3) containing values from 1 to 9
3. A 3x4 array filled with zeros
4. A 2x5 array filled with ones (data type: float32)
5. A 4x4 identity matrix
6. An array with values from 10 to 50 with step size 5
7. An array with 8 evenly spaced values between 0 and 1


In [2]:
import numpy as np
# 1. 1D array containng values from 0 to 9
arr1 = np.arange(0,10)
print("1D array (0to9):\n",arr1)
# 2. 2D array (3x3) containing values from 1 to 9
arr2 = np.arange(1,10).reshape(3,3)
print("\n2D array (3x3) with values 1 to 9 :\n",arr2)
# 3. A 3x4 array filled with zeros
arr3 = np.zeros((3, 4))
print("\n3x4 array filled with zeros:\n", arr3)
# 4. A 2x5 array filled with ones (float32)
arr4 = np.ones((2, 5), dtype=np.float32)
print("\n2x5 array filled with ones (float32):\n", arr4)
# 5. A 4x4 identity matrix
arr5 = np.eye(4)
print("\n4x4 identity matrix:\n", arr5)
# 6. An array with values from 10 to 50 with step size 5
arr6 = np.arange(10, 51, 5)
print("\nArray from 10 to 50 with step 5:\n", arr6)
# 7. An array with 8 evenly spaced values between 0 and 1
arr7 = np.linspace(0, 1, 8)
print("\n8 evenly spaced values between 0 and 1:\n", arr7)

1D array (0to9):
 [0 1 2 3 4 5 6 7 8 9]

2D array (3x3) with values 1 to 9 :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

3x4 array filled with zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2x5 array filled with ones (float32):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

4x4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Array from 10 to 50 with step 5:
 [10 15 20 25 30 35 40 45 50]

8 evenly spaced values between 0 and 1:
 [0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [ ]:
### Task 1.2: Explore array attributes (5 points)

Create a 3x4 array with values from 1 to 12. Print the following attributes:
- Shape
- Number of dimensions
- Total number of elements
- Data type
- Item size in bytes
- Total bytes consumed


In [3]:
import numpy as np
#create a 3x4 array with values from 1 to 12
arr=np.arange(1,13).reshape(3,4)
print("Array:\n",arr)
#Array attrbutes
print("shape:",arr.shape) #shape of the array
print("Number of dimensions:",arr.ndim) #Dimensions
print("Total number of elements:",arr.size) #Total number of elements
print("Data type :",arr.dtype)  #Data type 
print("Item size in bytes :",arr.itemsize) #size of an element
print("Total bytes consumed :",arr.nbytes) #Total memory used


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape: (3, 4)
Number of dimensions: 2
Total number of elements: 12
Data type : int64
Item size in bytes : 8
Total bytes consumed : 96


In [ ]:
Exercise 2: Indexing and Slicing (20 points)

### Task 2.1: Basic indexing (5 points)

Given the array: `arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])`

Write code to:
1. Access the first element
2. Access the last element using negative indexing
3. Access the 5th element

Then create a 2D array with shape (3, 4) and:
- Access the element at row 1, column 2
- Access the element at row 0, column 3
- Access the last element


In [5]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90,100])
# Accessing the first element 
print("first elemnet :",arr[0])
# Accessing the last element using negative indexing
print("Last element (negative indexing):",arr[-1])
#accessing the fifth element
print("5th element :",arr[4])
arr2d=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print("\n2D Array :\n",arr2d)
#Acess elements in 2d array
print("Element at row 1,column 2:",arr2d[1,2])
print("Element at row 0, column 3:",arr2d[0,3])
print("Last element:",arr2d[-1,-1])

first elemnet : 10
Last element (negative indexing): 100
5th element : 50

2D Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at row 1,column 2: 7
Element at row 0, column 3: 4
Last element: 12


In [ ]:
### Task 2.2: Slicing operations (8 points)

Given `arr = np.arange(0, 20)`:

1. Extract elements from index 5 to 15 (inclusive)
2. Extract every 3rd element from the array
3. Reverse the entire array using slicing

Create a 4x4 2D array and:
- Extract the first 2 rows and first 3 columns
- Extract the last 2 rows and last 2 columns
- Extract every other row with all columns

In [9]:
import numpy as np
arr = np.arange(0,20)
print("Original array:\n",arr)
#Extract elements from index 5 to 15
slice1 = arr[5:16]
print("\n Elements from index 5 to 15:",slice1)
# Extracting every 3rd element from the array 
slice2 = arr [::3]
print("\n Every 3rd element:",slice2)
#Reverse the entire array using slicing
slice3 = arr[::-1]
print("\n Reverse array :",slice3)
#Create a 4x4 2d array
arr2d = np.arange(1,17).reshape(4,4)
print("\n4x4 2D array:\n",arr2d)
#Extract the first 2 rows and 1ast 3 columns
slice4 = arr2d[:2,:3]
print("\n Firat 2 rows and last 3 columns :",slice4)
#Extract the last 2 rows and last 2 olumns
slice5 = arr2d[-2:,-2:]
print(" Last 2 rows and Last 2 columns:",slice5)
#Extract every other row with all columns
slice6 = arr2d[::2,:]
print("\n Every other row with all columns: ",slice6)


Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 Elements from index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]

 Every 3rd element: [ 0  3  6  9 12 15 18]

 Reverse array : [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

4x4 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 Firat 2 rows and last 3 columns : [[1 2 3]
 [5 6 7]]
 Last 2 rows and Last 2 columns: [[11 12]
 [15 16]]

 Every other row with all columns:  [[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
Task 2.3: Boolean and fancy indexing (7 points)

Given `arr = np.array([15, 23, 8, 42, 11, 37, 19, 5, 33, 28])`:

1. Use boolean indexing to extract all values greater than 20
2. Extract all even numbers
3. Extract values between 10 and 30 (inclusive)
4. Use fancy indexing to extract elements at indices 0, 3, 5, and 8

In [12]:
import numpy as np
arr=np.array([15,23,8,42,11,37,19,5,33,28])
print("Original array:",arr)
#Value grater than 20
greater_than_20=arr[arr>20]
print("\n Values greater then 20:",greater_than_20)
# Even numbers
even_number = arr[arr%2==0]
print("\n even numbers:",even_number)
#Values between 10 and 30
between_10_30 = arr[(arr >=10) & (arr <=30)]
print("values between 10 and 30:",between_10_30)
#Fancy indexing (specific indices)
fancy_indexing = arr[[0, 3, 5, 8]]
print("Elements at indices 0, 3, 5, and 8:", fancy_indexing)




Original array: [15 23  8 42 11 37 19  5 33 28]

 Values greater then 20: [23 42 37 33 28]

 even numbers: [ 8 42 28]
values between 10 and 30: [15 23 11 19 28]
Elements at indices 0, 3, 5, and 8: [15 42 37 33]


In [ ]:
 Exercise 3: Array Operations (15 points)

### Task 3.1: Arithmetic operations (8 points)

Given two arrays:
- `arr1 = np.array([10, 20, 30, 40, 50])`
- `arr2 = np.array([5, 10, 15, 20, 25])`

Perform the following operations:
1. Element-wise addition
2. Element-wise subtraction
3. Element-wise multiplication
4. Element-wise division
5. Square each element of arr1

Then perform scalar operations on arr1:
- Add 100 to all elements
- Multiply all elements by 3
- Divide all elements by 10

In [13]:
import numpy as np
# Given arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 10, 15, 20, 25])
print("Array 1:", arr1)
print("Array 2:", arr2)
# 1. Element-wise addition
add = arr1 + arr2
print("\nElement-wise addition:", add)
# 2. Element-wise subtraction
sub = arr1 - arr2
print("Element-wise subtraction:", sub)
# 3. Element-wise multiplication
mul = arr1 * arr2
print("Element-wise multiplication:", mul)
# 4. Element-wise division
div = arr1 / arr2
print("Element-wise division:", div)
# 5. Square each element of arr1
square = arr1 ** 2
print("Square of arr1 elements:", square)
# Scalar operations on arr1
add_scalar = arr1 + 100
print("\nAdd 100 to all elements:", add_scalar)
mul_scalar = arr1 * 3
print("Multiply all elements by 3:", mul_scalar)
div_scalar = arr1 / 10
print("Divide all elements by 10:", div_scalar)


Array 1: [10 20 30 40 50]
Array 2: [ 5 10 15 20 25]

Element-wise addition: [15 30 45 60 75]
Element-wise subtraction: [ 5 10 15 20 25]
Element-wise multiplication: [  50  200  450  800 1250]
Element-wise division: [2. 2. 2. 2. 2.]
Square of arr1 elements: [ 100  400  900 1600 2500]

Add 100 to all elements: [110 120 130 140 150]
Multiply all elements by 3: [ 30  60  90 120 150]
Divide all elements by 10: [1. 2. 3. 4. 5.]


In [ ]:
### Task 3.2: Universal functions (7 points)

Given `arr = np.array([1, 4, 9, 16, 25, 36])`:

1. Calculate square root of all elements
2. Calculate exponential (e^x) of all elements
3. Calculate natural logarithm of all elements

Create an array of angles `[0, π/6, π/4, π/3, π/2]` and:
- Calculate sine values
- Calculate cosine values

For the array `[1.23, 2.56, 3.89, 4.12]`:
- Round to nearest integer
- Apply floor operation
- Apply ceiling operation

In [20]:
import numpy as np
# Given array
arr = np.array([1, 4, 9, 16, 25, 36])
print("Original array:", arr)
# Square root of all elements
sqrt_arr = np.sqrt(arr)
print("\nSquare root:", sqrt_arr)
#Exponential (e^x) of all elements
exp_arr = np.exp(arr)
print("Exponential (e^x):", exp_arr)
#Natural logarithm of all elements
log_arr = np.log(arr)
print("Natural logarithm:", log_arr)
# Array of angles (in radians)
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2]) 
print("\nAngles (radians):\n", angles)
# Sine and Cosine values
sin_values = np.sin(angles)
cos_values = np.cos(angles)
print("Sine values:\n", sin_values)
print("Cosine values:\n", cos_values)
# Given decimal array
dec_arr = np.array([1.23, 2.56, 3.89, 4.12])
print("\nDecimal array:", dec_arr)
# Rounding operations
round_values = np.round(dec_arr)
floor_values = np.floor(dec_arr)
ceil_values = np.ceil(dec_arr)
print("Rounded values:", round_values)
print("Floor values:", floor_values)
print("Ceiling values:", ceil_values)


Original array: [ 1  4  9 16 25 36]

Square root: [1. 2. 3. 4. 5. 6.]
Exponential (e^x): [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]
Natural logarithm: [0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]

Angles (radians):
 [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine values:
 [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values:
 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Decimal array: [1.23 2.56 3.89 4.12]
Rounded values: [1. 3. 4. 4.]
Floor values: [1. 2. 3. 4.]
Ceiling values: [2. 3. 4. 5.]


In [ ]:
 Exercise 4: Array Manipulation (20 points)
### Task 4.1: Reshaping and transposing (10 points)
Create an array with values from 1 to 12, then:
1. Reshape it to 3x4
2. Reshape it to 2x6
3. Reshape it to 2x2x3 (3D array)
4. Transpose the 3x4 array
5. Flatten the 3x4 array back to 1D

In [17]:
import numpy as np
arr = np.arange(1,13)
print("Original 1D array:\n",arr)
#Reshape it in to 3x4 
arr_3x4 = arr.reshape(3,4)
print("Reshape to 3x4:\n",arr_3x4)
#Reshape it in to 2x6
arr_2x6 = arr.reshape(2,6)
print("Reshape to 2x6:\n",arr_2x6)
#Reshape it in to 2x2x3 (3D array)
arr_3d = arr.reshape(2,2,3)
print("\nReshaped to 2x2x3 (3d array):\n",arr_3d)
#Transpose in to 3x4 array
transpose_arr = arr_3x4.T
print("\n Transpose of 3x4 array:\n",transpose_arr)
#Flatten the 3x4 array back to 1D
flatten_arr = arr_3x4.flatten()
print("\nflattened 1D array:\n",flatten_arr)

Original 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshape to 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshaped to 2x2x3 (3d array):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

 Transpose of 3x4 array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

flattened 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
### Task 4.2: Stacking and splitting (10 points)

Create three 1D arrays: `[1, 2, 3]`, `[4, 5, 6]`, `[7, 8, 9]`

1. Stack them vertically to create a 3x3 array
2. Stack them horizontally to create a 1D array

Create an array from 1 to 12 and:
- Split it into 4 equal parts

Create a 4x4 array with values 1-16 and:
- Split it horizontally into 2 parts

In [21]:
import numpy as np
# Create three 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
#Stack vertically to create a 3x3 array
vertical_stack = np.vstack((a, b, c))
print("Vertical stacking (3x3):\n", vertical_stack)
#Stack horizontally to create a 1D array
horizontal_stack = np.hstack((a, b, c))
print("\nHorizontal stacking (1D):\n", horizontal_stack)
# Create an array from 1 to 12
arr = np.arange(1, 13)
print("\nArray from 1 to 12:", arr)
# Split into 4 equal parts
split_arr = np.split(arr, 4)
print("Split into 4 equal parts:", split_arr)
# Create a 4x4 array with values 1 to 16
arr2d = np.arange(1, 17).reshape(4, 4)
print("\n4x4 array:\n", arr2d)
# Split horizontally into 2 parts
horizontal_split = np.hsplit(arr2d, 2)
print("Horizontal split into 2 parts:")
for part in horizontal_split:
    print(part)


Vertical stacking (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Horizontal stacking (1D):
 [1 2 3 4 5 6 7 8 9]

Array from 1 to 12: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Split into 4 equal parts: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Horizontal split into 2 parts:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [ ]:
## Exercise 5: Statistical Operations (15 points)

### Task 5.1: Basic statistics (7 points)

Given `arr = np.array([12, 45, 23, 67, 34, 89, 56, 78, 90, 31])`:

Calculate and print:
1. Sum of all elements
2. Mean (average)
3. Median
4. Standard deviation
5. Variance
6. Minimum value
7. Maximum value
8. Index of minimum value
9. Index of maximum value

In [22]:
import numpy as np
arr = np.array([12,45,23,67,34,89,56,78,90,31])
#Calculate the operatons
#sum of the given elements
print("\n sum:",np.sum(arr))
#mean (average)
print("\n maean:",np.mean(arr))
#median 
print("\n median:",np.median(arr))
#Standard deviation
print("\n standard deviation:",np.std(arr))
#Variance
print("\n variance:",np.var(arr))
#Minimum value
print("\n minimum value:",np.min(arr))
#Maxmum value
print("\n maximum value:",np.max(arr))
#Index of minimum value
print(" \n Index of minimum value:",np.argmin(arr))
#Index of maximum value
print("\n Index of maximum value:",np.argmax(arr))



 sum: 525

 maean: 52.5

 median: 50.5

 standard deviation: 26.424420523447623

 variance: 698.25

 minimum value: 12

 maximum value: 90
 
 Index of minimum value: 0

 Index of maximum value: 8


In [ ]:

### Task 5.2: Axis-based statistics (8 points)

Create a 3x3 array:
```
[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]
```

Calculate:
1. Sum of all elements
2. Sum along axis 0 (column-wise sum)
3. Sum along axis 1 (row-wise sum)
4. Mean along axis 0
5. Mean along axis 1
6. Maximum values along axis 0
7. Maximum values along axis 1

In [24]:
import numpy as np
# Create 3x3 array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("Array:\n", arr)
#Sum of all elements
print("\nSum of all elements:", np.sum(arr))
#Sum along axis 0 (column-wise)
print("Sum along axis 0 (columns):", np.sum(arr, axis=0))
#Sum along axis 1 (row-wise)
print("Sum along axis 1 (rows):", np.sum(arr, axis=1))
#Mean along axis 0
print("Mean along axis 0:", np.mean(arr, axis=0))
#Mean along axis 1
print("Mean along axis 1:", np.mean(arr, axis=1))
#  Maximum values along axis 0
print("Maximum along axis 0:", np.max(arr, axis=0))
# Maximum values along axis 1
print("Maximum along axis 1:", np.max(arr, axis=1))


Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Sum of all elements: 450
Sum along axis 0 (columns): [120 150 180]
Sum along axis 1 (rows): [ 60 150 240]
Mean along axis 0: [40. 50. 60.]
Mean along axis 1: [20. 50. 80.]
Maximum along axis 0: [70 80 90]
Maximum along axis 1: [30 60 90]


In [ ]:
Exercise 6: Real-World Application - Student Grade Analysis (25 points)
You are given grade data for 5 students across 4 subjects (Math, Science, English, History):
python
grades = np.array([
    [85, 90, 78, 88],
    [92, 88, 95, 90],
    [76, 82, 80, 75],
    [88, 85, 90, 92],
    [95, 92, 88, 94]
]
**Tasks:**
1. **Calculate the average grade for each student** (5 points)
   - Output should show Student 1: X.XX, Student 2: Y.YY, etc.
2. **Calculate the average grade for each subject** (5 points)
   - Output: Math: X.XX, Science: Y.YY, etc.
3. **Find the highest and lowest grades in each subject** (5 points)
   - Output for each subject: Highest = X, Lowest = Y
4. **Identify students with an average grade above 85** (3 points)
   - Print student number and their average
5. **Calculate the overall class average** (2 points)
   - Average of all grades across all students
6. **Normalize all grades to a scale of 0-10** (5 points)
   - Use min-max normalization formula: (value - min) / (max - min) * 10
   - Print the normalized grades array
**Bonus:** Identify the top-performing student (+2 points)

In [29]:
import numpy as np
grades = np.array([
    [85, 90, 78, 88],
    [92, 88, 95, 90],
    [76, 82, 80, 75],
    [88, 85, 90, 92],
    [95, 92, 88, 94]
])
subjects = ["Math", "Science", "English", "History"]
# ---------------- Task 1 ----------------
print("\n" + "=" * 60)
print("\n Task 1: Student Averages ")
print("\n" + "=" * 60)
student_avg = np.mean(grades, axis=1)
for i, avg in enumerate(student_avg, start=1):
    print(f"Student {i}: {avg:.2f}")
# ---------------- Task 2 ----------------
print("\n" + "=" * 60)
print("\n Task 2: Subject Averages")
print("\n" + "=" * 60)
subject_avg = np.mean(grades, axis=0)
for subject, avg in zip(subjects, subject_avg):
    print(f"{subject}: {avg:.2f}")
# ---------------- Task 3 ----------------
print("\n" + "=" * 60)
print("\n Task 3: Highest and Lowest Grades per Subject ")
print("\n" + "=" * 60)
subject_max = np.max(grades, axis=0)
subject_min = np.min(grades, axis=0)
for i, subject in enumerate(subjects):
    print(f"{subject}: Highest = {subject_max[i]}, Lowest = {subject_min[i]}")
# ---------------- Task 4 ----------------
print("\n" + "=" * 60)
print("\n Task 4: Students with Average > 85 ")
print("\n" + "=" * 60)
for i, avg in enumerate(student_avg, start=1):
    if avg > 85:
        print(f"Student {i}: {avg:.2f}")
# ---------------- Task 5 ----------------
print("\n" + "=" * 60)
print("\nTask 5: Overall Class Average")
print("\n" + "=" * 60)
overall_avg = np.mean(grades)
print(f"Overall Class Average: {overall_avg:.2f}")
# ---------------- Task 6 ----------------
print("\n" + "=" * 60)
print("\nTask 6: Normalized Grades (0–10 Scale)")
print("\n" + "=" * 60)
min_val = np.min(grades)
max_val = np.max(grades)
normalized_grades = (grades - min_val) / (max_val - min_val) * 10
print(np.round(normalized_grades, 2))
# ---------------- Bonus ----------------
print("\n--- Bonus: Top-Performing Student ---")
top_student = np.argmax(student_avg) + 1
print(f"Top-performing student: Student {top_student}")




 Task 1: Student Averages 

Student 1: 85.25
Student 2: 91.25
Student 3: 78.25
Student 4: 88.75
Student 5: 92.25


 Task 2: Subject Averages

Math: 87.20
Science: 87.40
English: 86.20
History: 87.80


 Task 3: Highest and Lowest Grades per Subject 

Math: Highest = 95, Lowest = 76
Science: Highest = 92, Lowest = 82
English: Highest = 95, Lowest = 78
History: Highest = 94, Lowest = 75


 Task 4: Students with Average > 85 

Student 1: 85.25
Student 2: 91.25
Student 4: 88.75
Student 5: 92.25


Task 5: Overall Class Average

Overall Class Average: 87.15


Task 6: Normalized Grades (0–10 Scale)

[[ 5.   7.5  1.5  6.5]
 [ 8.5  6.5 10.   7.5]
 [ 0.5  3.5  2.5  0. ]
 [ 6.5  5.   7.5  8.5]
 [10.   8.5  6.5  9.5]]

--- Bonus: Top-Performing Student ---
Top-performing student: Student 5


In [ ]:
## Exercise 7: Challenge - Sales Data Analysis (30 points)

You are analyzing sales data for a company with 4 products over 6 months:

```python
sales_data = np.array([
    [120, 135, 150, 145, 160, 175],  # Product A
    [90, 95, 100, 110, 115, 120],    # Product B
    [150, 145, 155, 160, 170, 180],  # Product C
    [80, 85, 82, 88, 92, 95]         # Product D
])
```

**Tasks:**

1. **Calculate total sales for each product** (5 points)
   - Sum across all months for each product

2. **Calculate total sales for each month** (5 points)
   - Sum across all products for each month (Jan to Jun)

3. **Identify the month with the highest total sales** (4 points)
   - Print the month name and total sales

4. **Calculate the growth rate for each product** (6 points)
   - Growth rate = ((Last month - First month) / First month) × 100
   - Print as percentage for each product

5. **Find products with average monthly sales greater than 120k** (4 points)
   - Calculate average for each product
   - Print products meeting the criteria

6. **Calculate quarter-wise sales** (6 points)
   - Q1: January-March
   - Q2: April-June
   - Print sales for each product in each quarter

**Bonus:** Predict next month (July) sales for each product (+5 points)
- Use a simple method: average of last 2 months + average monthly growth


In [33]:
import numpy as np
# Sales data
sales_data = np.array([
    [120, 135, 150, 145, 160, 175],  # Product A
    [90, 95, 100, 110, 115, 120],    # Product B
    [150, 145, 155, 160, 170, 180],  # Product C
    [80, 85, 82, 88, 92, 95]         # Product D
])
products = ["Product A", "Product B", "Product C", "Product D"]
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
#Total sales for each product
print("\n" + "=" * 60)
print("\n--- Total Sales for Each Product ---")
print("\n" + "=" * 60)
product_total = np.sum(sales_data, axis=1)

for i in range(len(products)):
    print(products[i], ":", product_total[i])
# ------------------------------------------------
# 2. Total sales for each month
# ------------------------------------------------
print("\n" + "=" * 60)
print("\n Total Sales for Each Month")
print("\n" + "=" * 60)
month_total = np.sum(sales_data, axis=0)
for i in range(len(months)):
    print(months[i], ":", month_total[i])
# ------------------------------------------------
# 3. Month with highest total sales
# ------------------------------------------------
print("\n" + "=" * 60)
max_month_index = np.argmax(month_total)
print("\n Month with Highest Sales ")
print(months[max_month_index], "with sales", month_total[max_month_index])
# ------------------------------------------------
# 4. Growth rate for each product
# ------------------------------------------------
print("\n" + "=" * 60)
print("\n--- Growth Rate for Each Product (%) ---")
print("\n" + "=" * 60)
for i in range(len(products)):
    first = sales_data[i][0]
    last = sales_data[i][-1]
    growth = ((last - first) / first) * 100
    print(products[i], ":", round(growth, 2), "%")
# ------------------------------------------------
# 5. Products with average monthly sales > 120
# ------------------------------------------------
print("\n" + "=" * 60)
print("\n--- Products with Average Sales > 120 ---")
print("\n" + "=" * 60)
product_avg = np.mean(sales_data, axis=1)

for i in range(len(products)):
    if product_avg[i] > 120:
        print(products[i], "Average:", round(product_avg[i], 2))
# ------------------------------------------------
# 6. Quarter-wise sales
# ------------------------------------------------
print("\n" + "=" * 60)
print("\n--- Quarter-wise Sales ---")
print("\n" + "=" * 60)
# Q1 = Jan, Feb, Mar (0 to 2)
# Q2 = Apr, May, Jun (3 to 5)

for i in range(len(products)):
    q1 = np.sum(sales_data[i, 0:3])
    q2 = np.sum(sales_data[i, 3:6])
    print(products[i], "Q1:", q1, "Q2:", q2)
# ------------------------------------------------
# Bonus task : Predict July sales
# ------------------------------------------------
print("\n" + "=" * 60)
print("\n--- Predicted July Sales ---")
print("\n" + "=" * 60)
for i in range(len(products)):
    last_two_avg = (sales_data[i][-1] + sales_data[i][-2]) / 2
    monthly_growth = (sales_data[i][-1] - sales_data[i][0]) / 5
    july_prediction = last_two_avg + monthly_growth
    print(products[i], "Predicted July Sales:", round(july_prediction, 2))




--- Total Sales for Each Product ---

Product A : 885
Product B : 630
Product C : 960
Product D : 522


--- Total Sales for Each Month ---

Jan : 440
Feb : 460
Mar : 487
Apr : 503
May : 537
Jun : 570


--- Month with Highest Sales ---
Jun with sales 570


--- Growth Rate for Each Product (%) ---

Product A : 45.83 %
Product B : 33.33 %
Product C : 20.0 %
Product D : 18.75 %


--- Products with Average Sales > 120 ---

Product A Average: 147.5
Product C Average: 160.0


--- Quarter-wise Sales ---

Product A Q1: 405 Q2: 480
Product B Q1: 285 Q2: 345
Product C Q1: 450 Q2: 510
Product D Q1: 247 Q2: 275


--- Predicted July Sales ---

Product A Predicted July Sales: 178.5
Product B Predicted July Sales: 123.5
Product C Predicted July Sales: 181.0
Product D Predicted July Sales: 96.5
